/* ═══════════════════════════════════════════════════════════════
   Aurora — provenance chip (CLAUDE.md: every value carries provenance).
   Neutral for measured/modelled data; the "simulated" status colour for data
   that is not real (SIMULATED, HARDCODED-DEMO), so it can never pass as real.
   ═══════════════════════════════════════════════════════════════ */
import { Chip, Tooltip } from '@mui/material';

export const PROVENANCE = {
  REAL: { label: 'Real', help: 'Measured by a station sensor or the NCPOR AWS feed.' },
  REANALYSIS: { label: 'Reanalysis', help: 'ERA5 reanalysis (ECMWF) replayed for this station — modelled weather, not a station measurement.' },
  'MODEL-DERIVED': { label: 'Model-derived', help: 'Computed by the Aurora physics model from the inputs above. Parameters are estimates.' },
  SIMULATED: { label: 'Simulated', help: 'Generated by the simulator or the browser demo. Not real data.', notReal: true },
  'HARDCODED-DEMO': { label: 'Demo value', help: 'A built-in placeholder shown because no data is available. Not real data.', notReal: true },
  'OPERATOR-ENTERED': { label: 'Operator-entered', help: 'Typed in by an operator in the logistics ledger, not telemetry.' },
};

/**
 * @param {{kind: keyof PROVENANCE, subject?: string, detail?: string}} props
 * `subject` prefixes the label ("Generator · Model-derived"); `detail` extends the tooltip.
 */
export default function ProvenanceChip({ kind, subject, detail, ...rest }) {
  const p = PROVENANCE[kind] || { label: kind, help: '' };
  const label = subject ? `${subject} · ${p.label}` : p.label;
  return (
    <Tooltip title={[p.help, detail].filter(Boolean).join(' ')}>
      <Chip
        size="small"
        variant="outlined"
        label={label}
        data-provenance={kind}
        sx={(theme) => ({
          fontWeight: 500,
          color: p.notReal ? theme.vars.palette.status.simulated : theme.vars.palette.text.secondary,
          borderColor: p.notReal ? theme.vars.palette.status.simulated : theme.vars.palette.divider,
          backgroundColor: p.notReal ? theme.vars.palette.status.simulatedTint : 'transparent',
        })}
        {...rest}
      />
    </Tooltip>
  );
}
